### ISSUE TITLE
Please upgrade

### ISSUE THREAD

**Issue by rlee1990** [flutter-form-builder-ecosystem/form_builder_image_picker#11]
Please upgrade the package to support the latest version of Image_picker.

**Comment by guenth39** [comment]
Would be awesome! They just published version 0.8.1 with multi image support.

**Comment by NearHuscarl** [comment]
You can copy the [source files](https://github.com/danvick/form_builder_image_picker/tree/main/lib/src) and install the `image_picker` package in your project if you can't wait.

**Comment by ahmednfwela** [comment]
solved in #18
