### ISSUE TITLE
Unhandled Exception: A FocusNode was used after being disposed.Once you have called dispose() on a FocusNode, it can no longer be used

### ISSUE THREAD

**Issue by marcsinner** [flutter-form-builder-ecosystem/form_builder_image_picker#12]
The Exception is thrown when the page is popped. Probably the same issue as appearing recently in the form builder package.

Issue: 
https://github.com/danvick/flutter_form_builder/issues/795

fix:
https://github.com/danvick/flutter_form_builder/pull/799

**Comment by gomcodoctor** [comment]
same issue

**Comment by deandreamatias** [comment]
I think that this issue is solved by 
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/pull/1045 and available since version 3.0.0 of [form_builder_image_picker](https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker)
