### ISSUE TITLE
Dependency Error for form_builder_image_picker

### ISSUE THREAD

**Issue by purushakaram-admin** [flutter-form-builder-ecosystem/form_builder_image_picker#13]
Dear Team, I am using flutter_form_builder: ^6.0.1.  I also want to use Form Builder Image Picker.  However I get a dependency error since Image Picker depends on a much older version of flutter form builder.  Similarly Form Builder Image Picker depends on a much older version of Image Picker.  Can you please help by upgrading the Form Builder Image Picker, Form Builder File Picker, Form Builder Phone Number to the latest versions of the dependencies. Thanks a lot for your help in advance.

Regards, Kannan Govindan

**Comment by ahmednfwela** [comment]
solved in #18
