### ISSUE TITLE
App crashes

### ISSUE THREAD

**Issue by shabeenabarde** [flutter-form-builder-ecosystem/form_builder_image_picker#14]
The plugin works fine in my samsung note 8 with Android 8.0.0.

Although the same plugin crashes on my TECNO S2, Android version 8.1.0.

I think its some kind of memory issue because as soon as i click on the app and choose one of the options, lets say i choose "Camera", the terminal shows the following:
Service protocol connection closed.
[   +1 ms] Lost connection to device.
[   +5 ms] executing: /Users/shabinabarde/Library/Android/sdk/platform-tools/adb -s 03473258BQ000491 forward --list
[  +13 ms] Exit code 0 from: /Users/shabinabarde/Library/Android/sdk/platform-tools/adb -s 03473258BQ000491 forward --list
[        ] 03473258BQ000491 tcp:51935 tcp:40346
[   +2 ms] executing: /Users/shabinabarde/Library/Android/sdk/platform-tools/adb -s 03473258BQ000491 forward --remove tcp:51935
[  +20 ms] DevFS: Deleting filesystem on the device (file:///data/user/0/com.example.testforflutter2/code_cache/testforflutter2RYLGOW/testforflutter2/)
[ +255 ms] Ignored error while cleaning up DevFS: TimeoutException after 0:00:00.250000: Future not completed
[   +2 ms] executing: /Users/shabinabarde/Library/Android/sdk/platform-tools/adb -s 03473258BQ000491 forward --list
[  +14 ms] Exit code 0 from: /Users/shabinabarde/Library/Android/sdk/platform-tools/adb -s 03473258BQ000491 forward --list
[   +6 ms] "flutter run" took 288,425ms.
[ +266 ms] ensureAnalyticsSent: 259ms
[   +2 ms] Running shutdown hooks
[        ] Shutdown hooks complete
[        ] exiting with code 0

And then as soon as i click a picture, the app restarts from the very beginning!

**Comment by godwinaden** [comment]
I am having this same issue with version 2.0.0 of the plugin.
Any solution to this?

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/
form_builder_image_picker/issues/new/choose)
