### ISSUE TITLE
Bug on the web, show input html in webview 

### ISSUE THREAD

**Issue by cedricDevWP** [flutter-form-builder-ecosystem/form_builder_image_picker#21]
When i use this package i have a problem in my view, a input html is visible on the top left on Chrome :

![Capture d’écran 2022-01-17 à 16 27 30](https://user-images.githubusercontent.com/12508260/149797547-b24e33a2-903e-494e-aa33-1d4d2560d3d5.png)

**Comment by deandreamatias** [comment]
This still an issue?

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/
form_builder_image_picker/issues/new/choose)
