### ISSUE TITLE
How to convert XFile to MultipartFile

### ISSUE THREAD

**Issue by tonypottera24** [flutter-form-builder-ecosystem/form_builder_image_picker#30]
I'm using `form_builder_image_picker` with `Dio`, which is a package that handles HTTP request.
I'm wondering if there's any better way to case the `XFile` value given by `form_builder_image_picker` to `MultipartFile` (provided by `Dio`).
I tried to accomplish this by using the `valueTransformer` as follows.
```
valueTransformer: (images) async {
  if (images != null) {
    var multipartFile = [];
    for (final image in images) {
      multipartFile.add(await MultipartFile.fromFile(image.path));
    }
    return multipartFile;
  }
},
```

However, since valueTransformer does not wait for future. I'll get List<Future<MultipartFile>> in the end.
Does anyone have some advice?

**Comment by tonypottera24** [comment]
https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/648

In here, `flutter_form_builder` team said that `valueTransformer ` is built for type casting, but not for those async castings.

**Comment by deandreamatias** [comment]
You can separated this logic from widget. Maybe create a state with ChangeNotifier or other solution

**Comment by tonypottera24** [comment]
I see.
