### ISSUE TITLE
I just want to use camera feature. is it possible we can remove the gallery button on pop up after tapping container which contain camera icon ??

### ISSUE THREAD

**Issue by Harshhvermaa** [flutter-form-builder-ecosystem/form_builder_image_picker#42]
## Environment

**Package version:**

## Description

**What you'd like to happen:**

**Alternatives you've considered:**   

**Images:**

**Comment by deandreamatias** [comment]
Can create a new issue with details of this issue? Thanks

**Comment by deandreamatias** [comment]
Due to lack of response and an old error, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/flutter_form_builder/issues/new/choose)
