### ISSUE TITLE
Spanish Language Support

### ISSUE THREAD

**Issue by jamontesg** [flutter-form-builder-ecosystem/form_builder_image_picker#49]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

0.8.7+5

### What you'd like to happen

```Markdown
Get text  like camera and gallery   translated.  support for i10n
```

**Comment by deandreamatias** [comment]
Please, can add a image when do you want translate words?

**Comment by jamontesg** [comment]
![Screenshot_20230524-040638](https://github.com/flutter-form-builder-ecosystem/form_builder_image_picker/assets/16964566/3030bf73-632e-478c-b2cd-876a058f8efb)

**Comment by deandreamatias** [comment]
You can use `cameraLabel` y `galleryLabel` properties to show your own translations.

I will add dart doc comment to clarify this properties
