### ISSUE TITLE
Upgrade requirements to use image_picker 1.0.0

### ISSUE THREAD

**Issue by MonkeyDrone** [flutter-form-builder-ecosystem/form_builder_image_picker#50]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

4.0.0

### What you'd like to happen

```Markdown
I would like to update the plugin image_picker to version 1.0.0 but this is what I get when trying to use it.

Because form_builder_image_picker 4.0.0 depends on image_picker ^0.8.7+4 and no versions of form_builder_image_picker match >4.0.0 <5.0.0, form_builder_image_picker ^4.0.0 requires image_picker ^0.8.7+4.
So, because myworkapp depends on both form_builder_image_picker ^4.0.0 and image_picker ^1.0.0, version solving failed.

Would appreciate if this plugin could work with the requirements bump.

Thank you.
```

**Comment by deandreamatias** [comment]
I updated the image_picker version on main branch.
Please test if works like expected

**Comment by saidhasyim** [comment]
Hello, I face the same problem when using the latest version today. I'd love to test this. Would you guide me how to test this? sorry, I'm new to Flutter.

**Comment by saidhasyim** [comment]
works perfectly! thanks

**Comment by MonkeyDrone** [comment]
I can form it works with the latest image picker version. Thanks.

**Comment by qwezey** [comment]
when will this be released?
