### ISSUE TITLE
[Field name or General]: <Crop>

### ISSUE THREAD

**Issue by amotalles** [flutter-form-builder-ecosystem/form_builder_image_picker#56]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

4.0.0

### What you'd like to happen

```Markdown
please support cropping the image after picking .
```

**Comment by deandreamatias** [comment]
The goal of this package is picker a image to a form and no modify them. To allow this, use some package to crop image. Thanks
