### ISSUE TITLE
Cant use previewBuilder parameters

### ISSUE THREAD

**Issue by hazbu** [flutter-form-builder-ecosystem/form_builder_image_picker#58]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Package/Plugin version

4.0.0

### Platforms

- [X] Android
- [ ] iOS
- [ ] Linux
- [ ] MacOS
- [ ] Web
- [ ] Windows

### Flutter doctor

-

### Minimal code example

-

### Current Behavior

-

### Expected Behavior

-

### Steps To Reproduce

-

### Aditional information

The named parameter 'previewBuilder' isn't defined. (Documentation)  Try correcting the name to an existing named parameter's name, or defining a named parameter with the name 'previewBuilder'.

**Comment by deandreamatias** [comment]
I've remove the custom type PreviewBuilder. On next version, you can use `previewBuilder` property
