### ISSUE TITLE
Upgrade for flutter 2.0 and form_builder 5.0.0

### ISSUE THREAD

**Issue by faisalmushtaq007** [flutter-form-builder-ecosystem/form_builder_image_picker#7]
Because every version of form_builder_image_picker depends on flutter_form_builder ^4.2.0 and *project* depends on flutter_form_builder ^5.0.0, form_builder_image_picker is forbidden.
  So, because *project* depends on form_builder_image_picker ^0.1.2, version solving failed.

**Comment by danvick** [comment]
KIndly use `dependency_overrides` to solve this. 

Like so:
```dart
dependency_overrides:
    flutter_form_builder: ^5.0.0
```

**Comment by ahmednfwela** [comment]
solved in #18
