### ISSUE TITLE
 Unhandled Exception: This widget has been unmounted, so the State no longer has a context (and should be considered defunct). 

### ISSUE THREAD

**Issue by Clid3** [flutter-form-builder-ecosystem/form_builder_image_picker#8]
i get this error when using FormBuilderImagePicker in the same form with other FormBuilderTextFields, 
Any work around ?

**Comment by deandreamatias** [comment]
Due to lack of response, I will close this issue.
If the bug still exists, feel free to open a [new issue](https://github.com/flutter-form-builder-ecosystem/
form_builder_image_picker/issues/new/choose)
